/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as EditorTimelineRouteImport } from './routes/editor/timeline'
import { Route as EditorScenariosRouteImport } from './routes/editor/scenarios'
import { Route as EditorPlayersRouteImport } from './routes/editor/players'
import { Route as EditorEvidenceRouteImport } from './routes/editor/evidence'
import { Route as EditorPhasePhaseIdRouteImport } from './routes/editor/phase/$phaseId'
import { Route as EditorGameGameIdRouteImport } from './routes/editor/game/$gameId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorTimelineRoute = EditorTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EditorRoute,
} as any)
const EditorScenariosRoute = EditorScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => EditorRoute,
} as any)
const EditorPlayersRoute = EditorPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => EditorRoute,
} as any)
const EditorEvidenceRoute = EditorEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => EditorRoute,
} as any)
const EditorPhasePhaseIdRoute = EditorPhasePhaseIdRouteImport.update({
  id: '/phase/$phaseId',
  path: '/phase/$phaseId',
  getParentRoute: () => EditorRoute,
} as any)
const EditorGameGameIdRoute = EditorGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/settings': typeof SettingsRoute
  '/editor/evidence': typeof EditorEvidenceRoute
  '/editor/players': typeof EditorPlayersRoute
  '/editor/scenarios': typeof EditorScenariosRoute
  '/editor/timeline': typeof EditorTimelineRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/game/$gameId': typeof EditorGameGameIdRoute
  '/editor/phase/$phaseId': typeof EditorPhasePhaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/editor/evidence': typeof EditorEvidenceRoute
  '/editor/players': typeof EditorPlayersRoute
  '/editor/scenarios': typeof EditorScenariosRoute
  '/editor/timeline': typeof EditorTimelineRoute
  '/editor': typeof EditorIndexRoute
  '/editor/game/$gameId': typeof EditorGameGameIdRoute
  '/editor/phase/$phaseId': typeof EditorPhasePhaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/settings': typeof SettingsRoute
  '/editor/evidence': typeof EditorEvidenceRoute
  '/editor/players': typeof EditorPlayersRoute
  '/editor/scenarios': typeof EditorScenariosRoute
  '/editor/timeline': typeof EditorTimelineRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/game/$gameId': typeof EditorGameGameIdRoute
  '/editor/phase/$phaseId': typeof EditorPhasePhaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/settings'
    | '/editor/evidence'
    | '/editor/players'
    | '/editor/scenarios'
    | '/editor/timeline'
    | '/editor/'
    | '/editor/game/$gameId'
    | '/editor/phase/$phaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/editor/evidence'
    | '/editor/players'
    | '/editor/scenarios'
    | '/editor/timeline'
    | '/editor'
    | '/editor/game/$gameId'
    | '/editor/phase/$phaseId'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/settings'
    | '/editor/evidence'
    | '/editor/players'
    | '/editor/scenarios'
    | '/editor/timeline'
    | '/editor/'
    | '/editor/game/$gameId'
    | '/editor/phase/$phaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/timeline': {
      id: '/editor/timeline'
      path: '/timeline'
      fullPath: '/editor/timeline'
      preLoaderRoute: typeof EditorTimelineRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/scenarios': {
      id: '/editor/scenarios'
      path: '/scenarios'
      fullPath: '/editor/scenarios'
      preLoaderRoute: typeof EditorScenariosRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/players': {
      id: '/editor/players'
      path: '/players'
      fullPath: '/editor/players'
      preLoaderRoute: typeof EditorPlayersRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/evidence': {
      id: '/editor/evidence'
      path: '/evidence'
      fullPath: '/editor/evidence'
      preLoaderRoute: typeof EditorEvidenceRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/phase/$phaseId': {
      id: '/editor/phase/$phaseId'
      path: '/phase/$phaseId'
      fullPath: '/editor/phase/$phaseId'
      preLoaderRoute: typeof EditorPhasePhaseIdRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/game/$gameId': {
      id: '/editor/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/editor/game/$gameId'
      preLoaderRoute: typeof EditorGameGameIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorEvidenceRoute: typeof EditorEvidenceRoute
  EditorPlayersRoute: typeof EditorPlayersRoute
  EditorScenariosRoute: typeof EditorScenariosRoute
  EditorTimelineRoute: typeof EditorTimelineRoute
  EditorIndexRoute: typeof EditorIndexRoute
  EditorGameGameIdRoute: typeof EditorGameGameIdRoute
  EditorPhasePhaseIdRoute: typeof EditorPhasePhaseIdRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorEvidenceRoute: EditorEvidenceRoute,
  EditorPlayersRoute: EditorPlayersRoute,
  EditorScenariosRoute: EditorScenariosRoute,
  EditorTimelineRoute: EditorTimelineRoute,
  EditorIndexRoute: EditorIndexRoute,
  EditorGameGameIdRoute: EditorGameGameIdRoute,
  EditorPhasePhaseIdRoute: EditorPhasePhaseIdRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
